# Clustergram Example

In [1]:
%load_ext autoreload
%autoreload 2
%env ANYWIDGET_HMR=1

env: ANYWIDGET_HMR=1

In [2]:
import numpy as np
import pandas as pd
import celldega as dega

/Users/feni/Documents/celldega/dega/lib/python3.12/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.14.5 when it was built against 1.14.6, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "

In [3]:
from ipywidgets import Widget
Widget.close_all()

In [4]:
# generate random matrix
num_cols = 5
num_rows = 20

np.random.seed(seed=100)
mat = np.random.rand(num_rows, num_cols)

# make row and col labels
rows = range(num_rows)
cols = range(num_cols)
rows = [str(i) for i in rows]
cols = [str(i) for i in cols]

# make dataframe
df = pd.DataFrame(data=mat, columns=cols, index=rows)
df.shape

(20, 5)

In [5]:
meta_col = pd.DataFrame(index=df.columns.tolist())
top_cols = df.sum(axis=0).sort_values(ascending=False).index.tolist()[:3]
meta_col['type'] = 'low'
meta_col['experiment'] = 'a'
meta_col['test'] = 'something'
meta_col.loc[top_cols, 'type'] = 'high'
meta_col.loc['0', 'experiment'] = 'b'
meta_col.loc['1', 'experiment'] = 'b'
meta_col.loc['2', 'experiment'] = 'b'

meta_col['size'] = 0
meta_col.loc['0', 'size'] = 0
meta_col.loc['1', 'size'] = 1
meta_col.loc['2', 'size'] = 2
meta_col.loc['3', 'size'] = 7.5
meta_col.loc['4', 'size'] = -5

In [6]:
meta_row = pd.DataFrame(index=df.index.tolist())
top_rows = df.sum(axis=1).sort_values(ascending=False).index.tolist()[:5]
meta_row['type'] = 'low'
meta_row.loc['0', 'type'] = 'high'
meta_row.loc['1', 'type'] = 'high'
meta_row.loc['2', 'type'] = 'very-high'

In [7]:
df_colors = pd.DataFrame()
df_colors.loc['low', 'color'] = 'blue'
df_colors.loc['high', 'color'] = 'black'
df_colors.loc['very-high', 'color'] = 'yellow'
# df_colors.loc['a', 'color'] = 'orange'
# df_colors.loc['b', 'color'] = 'purple'

In [8]:
meta_col.head()

   type experiment       test  size
0  high          b  something   0.0
1  high          b  something   1.0
2   low          b  something   2.0
3  high          a  something   7.5
4   low          a  something  -5.0

In [9]:
meta_row.head()

        type
0       high
1       high
2  very-high
3        low
4        low

In [10]:
df.head()

          0         1         2         3         4
0  0.543405  0.278369  0.424518  0.844776  0.004719
1  0.121569  0.670749  0.825853  0.136707  0.575093
2  0.891322  0.209202  0.185328  0.108377  0.219697
3  0.978624  0.811683  0.171941  0.816225  0.274074
4  0.431704  0.940030  0.817649  0.336112  0.175410

In [11]:
df_colors.head()

            color
low          blue
high        black
very-high  yellow

In [12]:
mat = dega.clust.Matrix(
    df, 
    meta_col=meta_col, 
    col_attr=['experiment', 'type', 'size'],
    # col_attr=['experiment', 'type'],
    meta_row=meta_row, 
    name='parquet', 
    global_colors=df_colors
)
# mat.norm(axis='row', by='zscore')
mat.clust()
cgm_1 = dega.viz.Clustergram(
    matrix=mat, 
    width=500, 
    height=500
)
cgm_1

Clustergram(height=500, network_meta={'linkage': {}, 'row_attr': ['type'], 'col_attr': ['experiment', 'type', …

In [16]:
# cgm_1.close()