In [1]:
%load_ext autoreload
%autoreload 2
%env ANYWIDGET_HMR=1

env: ANYWIDGET_HMR=1

In [2]:
import numpy as np
import pandas as pd
import celldega as dega

In [3]:
from ipywidgets import Widget
Widget.close_all()

In [4]:
# generate random matrix
num_cols = 500
num_rows = 1000

np.random.seed(seed=100)
mat = np.random.rand(num_rows, num_cols)

# make row and col labels
rows = range(num_rows)
cols = range(num_cols)
rows = [str(i) for i in rows]
cols = [str(i) for i in cols]

# make dataframe
df = pd.DataFrame(data=mat, columns=cols, index=rows)
df.shape

(1000, 500)

In [5]:
meta_col = pd.DataFrame(index=df.columns.tolist())
top_cols = df.sum(axis=0).sort_values(ascending=False).index.tolist()[:5]
meta_col['type'] = 'low'
meta_col['experiment'] = 'a'
meta_col['test'] = 'something'
meta_col.loc[top_cols, 'type'] = 'high'
meta_col.loc['0', 'experiment'] = 'b'
meta_col.loc['1', 'experiment'] = 'b'
meta_col.loc['2', 'experiment'] = 'b'

In [6]:
meta_col.head()

  type experiment       test
0  low          b  something
1  low          b  something
2  low          b  something
3  low          a  something
4  low          a  something

In [7]:
meta_row = pd.DataFrame(index=df.index.tolist())
top_rows = df.sum(axis=1).sort_values(ascending=False).index.tolist()[:5]
meta_row['type'] = 'low'
meta_row.loc['0', 'type'] = 'high'
meta_row.loc['1', 'type'] = 'high'
meta_row.loc['2', 'type'] = 'very-high'

In [8]:
df_colors = pd.DataFrame()
df_colors.loc['low', 'color'] = 'blue'
df_colors.loc['high', 'color'] = 'black'
df_colors.loc['very-high', 'color'] = 'yellow'
# df_colors.loc['a', 'color'] = 'orange'
# df_colors.loc['b', 'color'] = 'purple'

In [9]:
meta_col

     type experiment       test
0     low          b  something
1     low          b  something
2     low          b  something
3     low          a  something
4     low          a  something
..    ...        ...        ...
495   low          a  something
496   low          a  something
497   low          a  something
498   low          a  something
499  high          a  something

[500 rows x 3 columns]

In [10]:
meta_row

          type
0         high
1         high
2    very-high
3          low
4          low
..         ...
995        low
996        low
997        low
998        low
999        low

[1000 rows x 1 columns]

In [11]:
df

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,0.543405,0.278369,0.424518,0.844776,0.004719,0.121569,0.670749,0.825853,0.136707,0.575093,...,0.757158,0.686172,0.856393,0.230878,0.519338,0.343333,0.658773,0.282790,0.502466,0.303278
1,0.552529,0.161127,0.568549,0.485710,0.127520,0.543692,0.200491,0.670161,0.558112,0.232378,...,0.616522,0.947579,0.906472,0.965094,0.337621,0.656403,0.291456,0.150869,0.036932,0.597964
2,0.027732,0.382237,0.953251,0.222199,0.305126,0.819320,0.578470,0.027617,0.954388,0.312139,...,0.279062,0.652883,0.382998,0.459917,0.117076,0.820498,0.026554,0.737706,0.858315,0.744456
3,0.106510,0.410900,0.337036,0.099837,0.923092,0.830182,0.553784,0.979481,0.823215,0.477880,...,0.630891,0.478955,0.140795,0.329110,0.775616,0.633031,0.105247,0.980898,0.364798,0.778565
4,0.259444,0.023003,0.654407,0.969216,0.698952,0.032054,0.003295,0.122310,0.729892,0.743647,...,0.514056,0.927185,0.958549,0.637225,0.810425,0.200090,0.919083,0.478302,0.635912,0.418574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.452351,0.107272,0.402613,0.561070,0.211027,0.266975,0.936888,0.549172,0.705522,0.299131,...,0.464319,0.776364,0.247712,0.485919,0.694655,0.400301,0.789691,0.417920,0.924677,0.217532
996,0.830361,0.922538,0.872661,0.933965,0.467994,0.216636,0.152380,0.252526,0.211126,0.731267,...,0.931373,0.135947,0.512773,0.559336,0.253575,0.525237,0.206648,0.263876,0.827428,0.828747
997,0.111321,0.400065,0.954879,0.082037,0.184362,0.611459,0.557353,0.180928,0.829128,0.470532,...,0.433940,0.731124,0.437903,0.674901,0.385684,0.915962,0.133351,0.368654,0.697746,0.226066
998,0.105283,0.071139,0.626755,0.968089,0.419372,0.435346,0.117211,0.753026,0.157066,0.632154,...,0.728839,0.990528,0.934744,0.208394,0.832231,0.714353,0.413764,0.939862,0.065200,0.521385
999,0.416804,0.876420,0.058889,0.775855,0.244510,0.622739,0.778653,0.289694,0.551955,0.663487,...,0.802516,0.238675,0.423408,0.220076,0.895098,0.046924,0.169185,0.755274,0.145708,0.578691

In [12]:
meta_col.head()

  type experiment       test
0  low          b  something
1  low          b  something
2  low          b  something
3  low          a  something
4  low          a  something

In [13]:
df_colors.head()

            color
low          blue
high        black
very-high  yellow

In [14]:
# mat.export_viz_parquet()

In [20]:
mat = dega.clust.Matrix(df, meta_col=meta_col, meta_row=meta_row, name='parquet') # , global_colors=df_colors)
mat.clust()
cgm_1 = dega.viz.Clustergram(matrix=mat, width=500, height=500)
cgm_1

Clustergram(height=500, network_meta={'linkage': {}, 'cat_colors': {'row': {}, 'col': {}}, 'matrix_colors': {'…

In [16]:
mat = dega.clust.Matrix(df, meta_col=meta_col, meta_row=meta_row, name='json') # , global_colors=df_colors)
mat.clust()
# cgm_1 = dega.viz.Clustergram(network=mat.viz, width=500, height=500)
cgm_2 = dega.viz.Clustergram(network=mat.viz, width=500, height=500)
cgm_2

Clustergram(height=500, network={'row_nodes': [{'name': '0', 'ini': 1000, 'clust': 232, 'rank': 369, 'rankvar'…

In [21]:
cgm_1.close()

In [19]:
# cgm_2.close()