In [1]:
%load_ext autoreload
%autoreload 2
%env ANYWIDGET_HMR=1

env: ANYWIDGET_HMR=1

In [2]:
import numpy as np
import pandas as pd
import celldega as dega

In [3]:
from ipywidgets import Widget
Widget.close_all()

In [4]:
# generate random matrix
num_cols = 5
num_rows = 10

np.random.seed(seed=100)
mat = np.random.rand(num_rows, num_cols)

# make row and col labels
rows = range(num_rows)
cols = range(num_cols)
rows = [str(i) for i in rows]
cols = [str(i) for i in cols]

# make dataframe
df = pd.DataFrame(data=mat, columns=cols, index=rows)
df.shape

(10, 5)

In [5]:
meta_col = pd.DataFrame(index=df.columns.tolist())
top_cols = df.sum(axis=0).sort_values(ascending=False).index.tolist()[:5]
meta_col['type'] = 'low'
meta_col['experiment'] = 'a'
meta_col['test'] = 'something'
meta_col.loc[top_cols, 'type'] = 'high'
meta_col.loc['0', 'experiment'] = 'b'
meta_col.loc['1', 'experiment'] = 'b'
meta_col.loc['2', 'experiment'] = 'b'

In [6]:
meta_col.head()

   type experiment       test
0  high          b  something
1  high          b  something
2  high          b  something
3  high          a  something
4  high          a  something

In [7]:
meta_row = pd.DataFrame(index=df.index.tolist())
top_rows = df.sum(axis=1).sort_values(ascending=False).index.tolist()[:5]
meta_row['type'] = 'low'
meta_row.loc['0', 'type'] = 'high'
meta_row.loc['1', 'type'] = 'high'
meta_row.loc['2', 'type'] = 'very-high'

In [8]:
df_colors = pd.DataFrame()
df_colors.loc['low', 'color'] = 'blue'
df_colors.loc['high', 'color'] = 'black'
df_colors.loc['very-high', 'color'] = 'yellow'
# df_colors.loc['a', 'color'] = 'orange'
# df_colors.loc['b', 'color'] = 'purple'

In [31]:
meta_col

   type experiment       test
0  high          b  something
1  high          b  something
2  high          b  something
3  high          a  something
4  high          a  something

In [30]:
meta_row

        type
0       high
1       high
2  very-high
3        low
4        low
5        low
6        low
7        low
8        low
9        low

In [29]:
df

          0         1         2         3         4
0  0.543405  0.278369  0.424518  0.844776  0.004719
1  0.121569  0.670749  0.825853  0.136707  0.575093
2  0.891322  0.209202  0.185328  0.108377  0.219697
3  0.978624  0.811683  0.171941  0.816225  0.274074
4  0.431704  0.940030  0.817649  0.336112  0.175410
5  0.372832  0.005689  0.252426  0.795663  0.015255
6  0.598843  0.603805  0.105148  0.381943  0.036476
7  0.890412  0.980921  0.059942  0.890546  0.576901
8  0.742480  0.630184  0.581842  0.020439  0.210027
9  0.544685  0.769115  0.250695  0.285896  0.852395

In [12]:
meta_col.head()

   type experiment       test
0  high          b  something
1  high          b  something
2  high          b  something
3  high          a  something
4  high          a  something

In [13]:
df_colors.head()

            color
low          blue
high        black
very-high  yellow

In [14]:
# cgm.close()

In [15]:
# mat = dega.clust.Matrix(df) # , global_colors=df_colors)
# mat.clust()
# cgm_1 = dega.viz.Clustergram(network=mat.viz, width=500, height=500)
# # cgm_1 = dega.viz.Clustergram(mat=mat, width=500, height=500)
# cgm_1

In [32]:
mat = dega.clust.Matrix(df, meta_col=meta_col, meta_row=meta_row, name='parquet') # , global_colors=df_colors)
mat.clust()
cgm_1 = dega.viz.Clustergram(parquet_data=mat.export_viz_parquet(), width=500, height=500)
cgm_1

parquet_data found in kwargs, using it to set up the widget

Clustergram(height=500, network_meta={'linkage': {}, 'cat_colors': {'row': {}, 'col': {}}, 'matrix_colors': {'…

In [26]:
mat = dega.clust.Matrix(df, meta_col=meta_col, meta_row=meta_row, name='json') # , global_colors=df_colors)
mat.clust()
# cgm_1 = dega.viz.Clustergram(network=mat.viz, width=500, height=500)
cgm_2 = dega.viz.Clustergram(network=mat.viz, width=500, height=500)
cgm_2

Clustergram(height=500, network={'row_nodes': [{'name': '0', 'ini': 10, 'clust': 0, 'rank': 3, 'rankvar': 3, '…

In [ ]:
# cgm_1.close()

In [27]:
# cgm_2.close()

In [69]:
!pip install pympler

Collecting pympler
  Downloading Pympler-1.1-py3-none-any.whl.metadata (3.6 kB)
Downloading Pympler-1.1-py3-none-any.whl (165 kB)
Installing collected packages: pympler
Successfully installed pympler-1.1

In [70]:
from pympler import asizeof

In [74]:
asizeof.asizeof(mat.viz)/1e6

19.142944

In [76]:
asizeof.asizeof(mat.export_viz_parquet())/1e6

2.835264

In [64]:
import sys

In [65]:
sys.getsizeof(mat.viz)

464

In [66]:
sys.getsizeof(mat.export_viz_parquet())

272

In [17]:
# mat = dega.clust.Matrix(df) # , global_colors=df_colors)
# mat.norm('col', 'zscore')
# mat.clust()
# cgm_1 = dega.viz.Clustergram(network=mat.viz, width=500, height=500)
# cgm_1

In [30]:
mat = dega.clust.Matrix(df.head(), name='tmp') # , global_colors=df_colors)
mat.norm('col', 'zscore')
mat.clust()
cgm_2 = dega.viz.Clustergram(network=mat.viz, width=500, height=500)
cgm_2

Clustergram(height=500, network={'row_nodes': [{'name': '0', 'ini': 5, 'clust': 3, 'rank': 0, 'rankvar': 4}, {…

In [20]:
mat = dega.clust.Matrix(df, name='something') # , global_colors=df_colors)
mat.norm('col', 'zscore')
mat.clust()
cgm_2 = dega.viz.Clustergram(network=mat.viz, width=500, height=500)
cgm_2

Clustergram(height=500, network={'row_nodes': [{'name': '0', 'ini': 50, 'clust': 14, 'rank': 12, 'rankvar': 26…

In [21]:
# cgm_2.close()

In [22]:
mat = dega.clust.Matrix(df) # , global_colors=df_colors)
mat.norm('col', 'zscore')
mat.clust()
cgm_2 = dega.viz.Clustergram(network=mat.viz, width=500, height=500)
cgm_2

Clustergram(height=500, network={'row_nodes': [{'name': '0', 'ini': 50, 'clust': 14, 'rank': 12, 'rankvar': 26…

In [23]:
mat = dega.clust.Matrix(df) # , global_colors=df_colors)
mat.norm('col', 'zscore')
mat.clust()
cgm_2 = dega.viz.Clustergram(network=mat.viz, width=500, height=500)
cgm_2

Clustergram(height=500, network={'row_nodes': [{'name': '0', 'ini': 50, 'clust': 14, 'rank': 12, 'rankvar': 26…